from bigQueryConverter.big_query_sql_script import SQLQueryConversion

queries = [
    'SELECT \n    "experienced_the_demo_demo_experienced_at_location" AS demo_location, \n    "stage_id", \n    COUNT("lead_id") AS number_of_leads \nFROM \n    `lead_details` \nGROUP BY \n    demo_location, \n    "stage_id";',
    'SELECT "registered_for_event_registered_event_name" AS Event_Name, AVG("rating_given_rating_given") AS Average_Rating\nFROM `lead_details`\nGROUP BY "registered_for_event_registered_event_name";',
    'SELECT assignee, COUNT(lead_id) AS "Total Leads", \n       SUM(CASE WHEN stage = \'Purchased\' THEN 1 ELSE 0 END) AS "Converted Leads",\n       (SUM(CASE WHEN stage = \'Purchased\' THEN 1 ELSE 0 END) / COUNT(lead_id)) * 100 AS "Conversion Percentage"\nFROM `lead_details`\nGROUP BY assignee;',
    "SELECT assignee, COUNT(lead_id), COUNT(*) as total_sales\nFROM lead_details\nWHERE stage = 'Purchased'\nGROUP BY assignee\nORDER BY total_sales DESC\nLIMIT 10;",
    'SELECT \n    "registered_for_event_registered_event_name" AS Event_Name, \n    COUNT("lead_id") AS Registration_Count\nFROM \n    `lead_details`\nWHERE \n    "registered_for_event_activity_datetime" >= CURDATE() - INTERVAL 10 DAY\nGROUP BY \n    "registered_for_event_registered_event_name";',
    "SELECT \n    DAYNAME(website_visited_activity_datetime) AS weekday,\n    COUNT(DISTINCT lead_id) AS unique_visits\nFROM \n    `lead_details`\nWHERE \n    website_visited_activity_datetime >= CURDATE() - INTERVAL 4 WEEK\nGROUP BY \n    weekday;",
    "SELECT \n    (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM `lead_details`)) AS percentage_checked_scorecard_highlights\nFROM \n    `lead_details`\nWHERE \n    scorecard_and_highlights_status_clicked_on_scorecard = 'Yes' \n    OR scorecard_and_highlights_status_clicked_on_match_highlights = 'Yes';",
    'SELECT "lead_id", "experienced_the_demo_reason_for_bad_experience"\nFROM `lead_details`\nWHERE "experienced_the_demo_reason_for_bad_experience" IS NOT NULL;',
    'SELECT "contact_state" AS Region, COUNT("lead_id") AS Total_Leads, \nSUM(CASE WHEN "stage_id" = \'Purchased\' THEN 1 ELSE 0 END) AS Converted_Leads \nFROM `lead_details` \nGROUP BY "contact_state";',
    'SELECT \n    MONTH(purchased_h_e_activity_datetime) AS "Month",\n    COUNT(lead_id) AS "Purchases"\nFROM \n    `lead_details`\nWHERE \n    stage = \'Purchased\'\nGROUP BY \n    MONTH(purchased_h_e_activity_datetime)\nORDER BY \n    MONTH(purchased_h_e_activity_datetime);',
    'SELECT \n    MONTH(record_created_at) AS "Month",\n    COUNT(lead_id) AS "Purchases"\nFROM \n    `lead_details`\nWHERE \n    stage_id = \'1338b2bd-91b1-4ece-9131-960b92437881\'\nGROUP BY \n    MONTH(record_created_at)\nORDER BY \n    MONTH(record_created_at);',
    "SELECT assignee, COUNT(lead_id) as projected_sales\nFROM lead_details\nWHERE probable_purchase_date BETWEEN DATE_FORMAT(NOW() ,'%Y-%m-01') AND LAST_DAY(NOW())\nAND stage = 'Committed to Purchase'\nGROUP BY assignee;",
    'SELECT \n    "experienced_the_demo_demo_experienced_at_location" AS demo_locations, \n    "stage_id", \n    COUNT("lead_id") AS number_of_leads \nFROM \n    `lead_details` \nGROUP BY \n    demo_location, \n    "stage_id";',
    'SELECT "registered_for_event_registered_event_name" AS Event_Name, AVG("rating_given_rating_given") AS Average_Rating\nFROM `lead_details`\nGROUP BY "registered_for_event_registered_event_name";',
    'SELECT assignee, COUNT(lead_id) AS "Total Leads", \n       SUM(CASE WHEN stage = \'Purchased\' THEN 1 ELSE 0 END) AS "Converted Leads",\n       (SUM(CASE WHEN stage = \'Purchased\' THEN 1 ELSE 0 END) / COUNT(lead_id)) * 100 AS "Conversion Percentage"\nFROM `lead_details`\nGROUP BY assignee;',
    "SELECT assignee, COUNT(lead_id), COUNT(*) as total_sales\nFROM lead_details\nWHERE stage = 'Purchased'\nGROUP BY assignee\nORDER BY total_sales DESC\nLIMIT 10;",
    'SELECT \n    "registered_for_event_registered_event_name" AS Event_Name, \n    COUNT("lead_id") AS Registration_Count\nFROM \n    `lead_details`\nWHERE \n    "registered_for_event_activity_datetime" >= CURDATE() - INTERVAL 10 DAY\nGROUP BY \n    "registered_for_event_registered_event_name";',
    "SELECT \n    DAYNAME(website_visited_activity_datetime) AS weekday,\n    COUNT(DISTINCT lead_id) AS unique_visits\nFROM \n    `lead_details`\nWHERE \n    website_visited_activity_datetime >= CURDATE() - INTERVAL 4 WEEK\nGROUP BY \n    weekday;",
    "SELECT \n    (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM `lead_details`)) AS percentage_checked_scorecard_highlights\nFROM \n    `lead_details`\nWHERE \n    scorecard_and_highlights_status_clicked_on_scorecard = 'Yes' \n    OR scorecard_and_highlights_status_clicked_on_match_highlights = 'Yes';",
    'SELECT "lead_id", "experienced_the_demo_reason_for_bad_experience"\nFROM `lead_details`\nWHERE "experienced_the_demo_reason_for_bad_experience" IS NOT NULL;',
    'SELECT "contact_state" AS Region, COUNT("lead_id") AS Total_Leads, \nSUM(CASE WHEN "stage_id" = \'Purchased\' THEN 1 ELSE 0 END) AS Converted_Leads \nFROM `lead_details` \nGROUP BY "contact_state";',
    'SELECT \n    MONTH(purchased_h_e_activity_datetime) AS "Month",\n    COUNT(lead_id) AS "Purchases"\nFROM \n    `lead_details`\nWHERE \n    stage = \'Purchased\'\nGROUP BY \n    MONTH(purchased_h_e_activity_datetime)\nORDER BY \n    MONTH(purchased_h_e_activity_datetime);',
    'SELECT \n    MONTH(record_created_at) AS "Month",\n    COUNT(lead_id) AS "Purchases"\nFROM \n    `lead_details`\nWHERE \n    stage_id = \'1338b2bd-91b1-4ece-9131-960b92437881\'\nGROUP BY \n    MONTH(record_created_at)\nORDER BY \n    MONTH(record_created_at);',
    "SELECT assignee, COUNT(lead_id) as projected_sales\nFROM lead_details\nWHERE probable_purchase_date BETWEEN DATE_FORMAT(NOW() ,'%Y-%m-01') AND LAST_DAY(NOW())\nAND stage = 'Committed to Purchase'\nGROUP BY assignee;",
    "SELECT stage_id from lead_details WHERE stage_id <= 2;",
    "SELECT stage_id from lead_details WHERE abc >=3;",
    "SELECT stage_id from lead_details WHERE def < 4;",
    "SELECT stage_id from lead_details WHERE pqr > 6;",
    "SELECT MONTH(record_created_at) as record_created_month FROM lead_details GROUP BY MONTH(record_created_at);",
    "SELECT stage_id from lead_details WHERE stage_id like 'abc*';",
    "SELECT stage_id from lead_details WHERE stage_id <= 2;",
    "SELECT stage_id from lead_details WHERE abc >=3;",
    "SELECT stage_id from lead_details WHERE def < 4;",
    "SELECT stage_id from lead_details WHERE pqr > 6;",
    "SELECT YEAR(record_created_at) from lead_details;",
    "SELECT WEEK(record_created_at) from lead_details;",
    "SELECT MONTH(record_created_at) from lead_details;",
    "SELECT WEEKDAY(record_created_at) from lead_details;",
    "SELECT lead_id from lead_details WHERE YEAR(record_created_at) = 2023;",
    "SELECT lead_id from lead_details WHERE YEAR(record_created_at) <= 2023;",
    "SELECT lead_id from lead_details WHERE YEAR(record_created_at) >= 2023;",
    "SELECT lead_id from lead_details WHERE YEAR(record_created_at) < 2023;",
    "SELECT lead_id from lead_details WHERE YEAR(record_created_at) > 2023;",
    "SELECT lead_id from lead_details WHERE MONTH(record_created_at) = 3;",
    "SELECT lead_id from lead_details WHERE MONTH(record_created_at) <= 3;",
    "SELECT lead_id from lead_details WHERE MONTH(record_created_at) >= 3;",
    "SELECT lead_id from lead_details WHERE MONTH(record_created_at) < 3;",
    "SELECT lead_id from lead_details WHERE MONTH(record_created_at) > 3;",
    "SELECT lead_id from lead_details WHERE WEEK(record_created_at) = 10;",
    "SELECT lead_id from lead_details WHERE WEEK(record_created_at) <= 10;",
    "SELECT lead_id from lead_details WHERE WEEK(record_created_at) >= 10;",
    "SELECT lead_id from lead_details WHERE WEEK(record_created_at) < 10;",
    "SELECT lead_id from lead_details WHERE WEEK(record_created_at) > 10;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) = 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) < 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) > 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) >= 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) <= 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) = 2023;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) < 2023;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) > 2023;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) >= 2023;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) <= 2023;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) = 1",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) < 1",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) > 1",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) >= 1",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) <= 1",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) = 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) = WEEKDAY(record_created_at);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) = WEEKDAY(CURRENT_DATE);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) = WEEK(record_created_at);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) = WEEK(CURRENT_DATE);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) = MONTH(record_created_at);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) = MONTH(CURRENT_DATE);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) = YEAR(record_created_at);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) = YEAR(CURRENT_DATE);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) < 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) > 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) >= 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) <= 1;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) = '2023-01-01'",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) < '2023-01-01'",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) > '2023-01-01'",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) >= '2023-01-01'",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) <= '2023-01-01'",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) IN (1, 2);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) IN (2023, 2024);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) IN (1, 2);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) IN (1, 2);",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) IN ('2023-01-01', '2023-01-02');",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE MONTH(record_created_at) BETWEEN 1 AND 2;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE YEAR(record_created_at) BETWEEN 2023 AND 2024;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEK(record_created_at) BETWEEN 1 AND 2;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE WEEKDAY(record_created_at) BETWEEN 1 AND 2;",
    "SELECT COUNT(*) as 'leads_count' FROM lead_details WHERE DATE(record_created_at) BETWEEN '2023-01-01' AND '2023-01-02';",
]

table_mappings = {"lead_details": "lead"}

value_mappings = {
    "stage_id": {"01b16473-72f1-46f8-b590-e279d363fabe": "Purchased"}
}

whitelist_cols = [
    "stage_id",
    "assignee",
    "lead_id",
    "experienced_the_demo_reason_for_bad_experience",
]

field_mappings = [
    {
        "sales_template_name": "Contact",
        "normalized_name": "contact",
        "sales_template_id": "eac72cc0-2639-4ee5-814f-1524530d01bb",
        "sales_template_type": "CONTACT",
        "fields": [
            {
                "field_name": "Last Name",
                "normalized_name": "last_name",
                "field_id": "9f619830-8678-4ea3-8acb-14f46da05294",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "First Name",
                "normalized_name": "first_name",
                "field_id": "bb44d230-fe3b-4b15-9ae8-5757ec5295fa",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Occupation",
                "normalized_name": "occupation",
                "field_id": "dcc72a76-b1ee-4637-a24b-7bfe92aa61e4",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Gender",
                "normalized_name": "gender",
                "field_id": "32abedc2-f7a3-4ea7-8ff9-230ab902cb21",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Born on or Before 1990?",
                "normalized_name": "born_on_or_before_1990",
                "field_id": "ba58211d-d4fd-47b8-ac82-32794f0520f8",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Phone Number",
                "normalized_name": "phone_number",
                "field_id": "46f8d28a-cd8f-4060-b384-3b3a047c2dae",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "WhatsApp Content Provided?",
                "normalized_name": "whatsapp_content_provided",
                "field_id": "3b7cdffd-c6be-452d-8abd-7e6734c4b001",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Assignee",
                "normalized_name": "assignee",
                "field_id": "159fd9c8-061c-4cca-bbba-fcb223db0973",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #1 Designation",
                "normalized_name": "contact_1_designation",
                "field_id": "0301cadb-9ca5-4558-b76b-e8b5c3418935",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 City",
                "normalized_name": "contact_1_city",
                "field_id": "0c34f16e-021b-48fc-86af-ce4712fb2a24",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact Type",
                "normalized_name": "contact_type",
                "field_id": "9d056362-feec-479f-b75d-5796c31cb10f",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Contact #2 Designation",
                "normalized_name": "contact_2_designation",
                "field_id": "969f6845-4925-4525-b712-c4d0deb08ccc",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #2 Phone Number",
                "normalized_name": "contact_2_phone_number",
                "field_id": "7718a0f8-53b4-4d69-a90e-465351097f5a",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Contact #3 Phone Number",
                "normalized_name": "contact_3_phone_number",
                "field_id": "94ab4d33-a8c8-4a59-96b0-d57584b950c4",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Other Host Type",
                "normalized_name": "other_host_type",
                "field_id": "7030c99b-757d-4194-a54f-cc20192d9633",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #1 Email",
                "normalized_name": "contact_1_email",
                "field_id": "3cae0e07-7dad-4745-9a22-54eb94c42005",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #2 Email",
                "normalized_name": "contact_2_email",
                "field_id": "72bafc4d-970c-4599-b991-d2cf434fa296",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #3 City",
                "normalized_name": "contact_3_city",
                "field_id": "1608be46-268e-4b9f-8240-8dfdc1b32c46",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Name",
                "normalized_name": "contact_3_name",
                "field_id": "3bb11a7e-f5f3-4dbc-adec-223eaac2c5db",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Host Type",
                "normalized_name": "host_type",
                "field_id": "58d8fe94-6c7c-4db6-a7d9-5c899054ff01",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Contact #3 Designation",
                "normalized_name": "contact_3_designation",
                "field_id": "d6b17b0b-6181-4c30-a8d4-e904061f9776",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Phone Number",
                "normalized_name": "contact_1_phone_number",
                "field_id": "a7d9d943-f151-4d78-bfec-7fc90f09d115",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Contact #2 Type - DM or POC",
                "normalized_name": "contact_2_type___dm_or_poc",
                "field_id": "fdfba2f4-4bcf-4a35-b41d-4ec9723af1a1",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Type - DM or POC",
                "normalized_name": "contact_3_type___dm_or_poc",
                "field_id": "b710c70e-6012-4a04-b523-38427cb5e937",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Type - DM or POC",
                "normalized_name": "contact_1_type___dm_or_poc",
                "field_id": "c9f80c32-1ebe-4b32-a88f-ce74fb4b209d",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Email",
                "normalized_name": "contact_3_email",
                "field_id": "a7d9b799-e3ed-47a3-af12-0511ee916142",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #2 City",
                "normalized_name": "contact_2_city",
                "field_id": "e9115863-b73b-4c87-a7e5-3b10ec2f789c",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Name",
                "normalized_name": "contact_1_name",
                "field_id": "c5898766-1d52-44f6-986a-e5ef281014fc",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #2 Name",
                "normalized_name": "contact_2_name",
                "field_id": "bb628f34-dfe3-4e05-ae5d-9581fbc05e5c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Address Line 1",
                "normalized_name": "address_line_1",
                "field_id": "132ef3cc-b5bc-46f6-a28d-fdc4dea01b16",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Address Line 2",
                "normalized_name": "address_line_2",
                "field_id": "88d4799e-173f-4745-95f5-db54829d8f8a",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "City",
                "normalized_name": "city",
                "field_id": "f603677d-eabb-4e01-86fd-9bff0d621dcc",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "State",
                "normalized_name": "state",
                "field_id": "54933d2b-d5f4-4cb6-bc60-67223dae60e3",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Pincode",
                "normalized_name": "pincode",
                "field_id": "c47f48c8-25a2-4763-a689-347f1b9697e2",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Landmark",
                "normalized_name": "landmark",
                "field_id": "9793925e-bc70-4ea8-b0a6-d3a9654135f6",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Custom Id",
                "normalized_name": "custom_id",
                "field_id": "9179a996-4405-493e-bd84-e47189c6b1e8",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Email",
                "normalized_name": "email",
                "field_id": "e6dadd33-ae80-4a84-94dc-ccbe14971c33",
                "field_type": "EMAIL",
            },
        ],
    },
    {
        "sales_template_name": "Lead",
        "normalized_name": "lead",
        "sales_template_id": "cd16c749-3d54-4df8-b153-60fdec54aa5a",
        "sales_template_type": "LEAD",
        "fields": [
            {
                "field_name": "Assignee",
                "normalized_name": "assignee",
                "field_id": "47ed0a89-e27b-4d23-b208-773dc0db29af",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Score",
                "normalized_name": "score",
                "field_id": "7af7d89c-e7fa-4dbf-bcdf-7431e457153a",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Stage",
                "normalized_name": "stage",
                "field_id": "9215af29-0ac2-4ef2-a43b-2eb0f45e5537",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced at Location",
                "normalized_name": "demo_experienced_at_location",
                "field_id": "fe69eb23-96a2-41bc-9e56-79795423215d",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced at City",
                "normalized_name": "demo_experienced_at_city",
                "field_id": "6a13b165-a415-40b5-83a1-f69bd66d3185",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Runs Scored in Demo",
                "normalized_name": "runs_scored_in_demo",
                "field_id": "e1a0e51d-cacb-4382-b78e-2a57ed676f3a",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Reason for Bad Experience",
                "normalized_name": "reason_for_bad_experience",
                "field_id": "c5889dda-7370-4d2d-a659-891d12bebc99",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "H.E Page Visited On",
                "normalized_name": "h_e_page_visited_on",
                "field_id": "4206a12d-4d1c-4a7c-9c72-38c3e86664a3",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Registered Event Name",
                "normalized_name": "registered_event_name",
                "field_id": "d70ea271-d85d-4591-9375-3b087ec177cb",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Registered Event ID",
                "normalized_name": "registered_event_id",
                "field_id": "fd7f1c16-2642-4b9b-a46f-369f598bdee1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Interest Status",
                "normalized_name": "interest_status",
                "field_id": "a3fef0f6-e108-4213-b279-e187dc412ce2",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Rating Given",
                "normalized_name": "rating_given",
                "field_id": "e6b1e1c6-fc5b-4878-9dc0-e1196da4f1af",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Challenges faced to purchase game",
                "normalized_name": "challenges_faced_to_purchase_game",
                "field_id": "1cedbe99-d4d3-4fa1-8d69-69ccb51edd81",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Conversion Probability Rating",
                "normalized_name": "conversion_probability_rating",
                "field_id": "1006b2d1-fa37-4a64-bc26-970c2302b535",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "What motivated him/her?",
                "normalized_name": "what_motivated_him_or_her",
                "field_id": "13c8977e-a839-4a26-be1f-e16713fd244f",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Next Follow-up Date",
                "normalized_name": "next_follow_up_date",
                "field_id": "b6f06fa9-63d1-41d1-b6c1-624c2f9ad0a6",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "H.E Page Visited",
                "normalized_name": "h_e_page_visited",
                "field_id": "74f1c8d9-e70c-487b-88ec-7c199da2abf9",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Commitment Status",
                "normalized_name": "commitment_status",
                "field_id": "f5eceed1-8ea5-427b-ad34-6962ebad8a6a",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Call Status",
                "normalized_name": "call_status",
                "field_id": "53775f64-77d7-4b1c-bd2a-ff72d30bfdf6",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "UTM Campaign",
                "normalized_name": "utm_campaign",
                "field_id": "4758aae6-f974-428e-ac6c-bbb5aabeb280",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Content",
                "normalized_name": "utm_content",
                "field_id": "862161ea-2791-4fbf-8c69-f38ad2a15ab0",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Medium",
                "normalized_name": "utm_medium",
                "field_id": "bcc14e30-cdd4-44f1-86e4-496ef0617c42",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Source",
                "normalized_name": "utm_source",
                "field_id": "33c8801d-427a-4e86-82fc-30b8b3f79115",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Term",
                "normalized_name": "utm_term",
                "field_id": "44f8808c-a018-442b-8254-9efca587cbd0",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Game Mode",
                "normalized_name": "game_mode",
                "field_id": "e34e120f-9e49-40e0-86ba-929d1c87dcdd",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Questions Asked",
                "normalized_name": "questions_asked",
                "field_id": "71eff3bf-516c-440a-ac36-dcc8249faf22",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Probable Purchase date",
                "normalized_name": "probable_purchase_date",
                "field_id": "03d6f1ef-e01c-4ba7-aa2a-3ed5fa818cd8",
                "field_type": "DATE",
            },
            {
                "field_name": "Describe the Resistance",
                "normalized_name": "describe_the_resistance",
                "field_id": "e2df053a-4fdf-4dfe-8051-e45940484d3a",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Resistance to buy",
                "normalized_name": "resistance_to_buy",
                "field_id": "a911af61-0118-4ab1-92ea-2644021b5a44",
                "field_type": "MULTI_SELECT",
            },
            {
                "field_name": "Device Code",
                "normalized_name": "device_code",
                "field_id": "aa88d028-5d0f-4e03-8ead-7a2771d71d52",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "OperatorNumber",
                "normalized_name": "operatornumber",
                "field_id": "038f38d3-1034-41f8-bcd9-124ff089df14",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "OperatorName",
                "normalized_name": "operatorname",
                "field_id": "fe7b906e-2e5d-4067-972b-2d0f4f2abc86",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Lead Interest Status",
                "normalized_name": "bda_or_pes_lead_interest_status",
                "field_id": "42c4517c-330b-48dd-8684-fcd582159f56",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "BDA / PES Mobile Number",
                "normalized_name": "bda_or_pes_mobile_number",
                "field_id": "0275a374-7325-4f87-8128-13836a734141",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Remarks",
                "normalized_name": "bda_or_pes_remarks",
                "field_id": "910c02ea-4128-48ea-97c3-e7aa03ef5ca9",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "BDA / PES Name",
                "normalized_name": "bda_or_pes_name",
                "field_id": "ac4f3c1d-6472-48f0-84e4-ffec01e18ed1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Lead contest played status",
                "normalized_name": "lead_contest_played_status",
                "field_id": "e11385b7-c95c-48b9-8b8b-df073dfbbcab",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Scorecard",
                "normalized_name": "clicked_on_scorecard",
                "field_id": "eab80297-56f7-498e-af2a-e913ff875086",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Match Highlights",
                "normalized_name": "clicked_on_match_highlights",
                "field_id": "29cb548e-e9e6-481b-9954-6debc5717ce2",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "BDA / PES Feedback on Lead",
        "normalized_name": "bda_or_pes_feedback_on_lead",
        "sales_template_id": "08f5156d-b406-42b3-8bee-1bb5a9deafc7",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "17235138-371f-4d4c-a6b4-8784941ef54b",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "BDA / PES Lead Interest Status",
                "normalized_name": "bda_or_pes_lead_interest_status",
                "field_id": "ecb8c7b2-4f42-430c-8b2b-0a34f38d54f2",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "BDA / PES Mobile Number",
                "normalized_name": "bda_or_pes_mobile_number",
                "field_id": "1602f126-efce-40a8-836b-e1ca8942a82c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Remarks",
                "normalized_name": "bda_or_pes_remarks",
                "field_id": "a86de4c9-d254-4650-9d4f-ef68bab4b9de",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "BDA / PES Name",
                "normalized_name": "bda_or_pes_name",
                "field_id": "241cbd63-010c-4d6a-b097-fa25d3e33334",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Experienced the Demo",
        "normalized_name": "experienced_the_demo",
        "sales_template_id": "ef2368ab-3be4-4d12-ab35-7429f8724148",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "56bbbdef-6703-4552-91d9-fd6cd21978a1",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Demo Experienced At Location",
                "normalized_name": "demo_experienced_at_location",
                "field_id": "aa7f9b1f-45f4-4082-8e1f-5a10b1c300cf",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced At City",
                "normalized_name": "demo_experienced_at_city",
                "field_id": "a437d302-4e84-44be-a7a4-bd0a01ccac37",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Runs Scored in the Demo",
                "normalized_name": "runs_scored_in_the_demo",
                "field_id": "cbb6a178-e64b-49ec-9e8f-3d91c1421795",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "43a79ded-a615-487c-b11a-8e78e581c673",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Game Mode",
                "normalized_name": "game_mode",
                "field_id": "b3b06ea4-faf5-4ded-b574-a4c29c7b568f",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Operator Number",
                "normalized_name": "operator_number",
                "field_id": "dfd2d31a-cc4a-4a27-a141-22dd0acabb8a",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Operator Name",
                "normalized_name": "operator_name",
                "field_id": "dc4b5689-df1b-47c9-a4d4-fc80bdb6f718",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Device Code",
                "normalized_name": "device_code",
                "field_id": "4d0f0980-d45f-468a-9c97-4098bd12b471",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Interested in H.E",
        "normalized_name": "interested_in_h_e",
        "sales_template_id": "2a3301a9-4a39-4f30-974d-8429a55c4424",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "c24b3a4b-ed65-4b10-ab08-6263258d0077",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Interest Status",
                "normalized_name": "interest_status",
                "field_id": "fb5316e3-653c-4950-ba1d-9c44db9c459e",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "5d0d0c2e-a176-44e1-9426-5964551bd27f",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Player Contest Completion Status",
        "normalized_name": "player_contest_completion_status",
        "sales_template_id": "3ab6eff6-d220-4936-bbc4-df7a8bd6bee8",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "deeeaa4f-69d2-4748-b5cb-166f19a55687",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Lead contest played status",
                "normalized_name": "lead_contest_played_status",
                "field_id": "d23cdd58-37f0-4c4b-8b43-11416b7c62e3",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "Purchased H.E",
        "normalized_name": "purchased_h_e",
        "sales_template_id": "5f0a87f1-726b-4352-87ef-21300f6154f1",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "4cce297f-586c-4fda-aaa4-46289864842e",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Purchase Order ID",
                "normalized_name": "purchase_order_id",
                "field_id": "afec3981-1093-4a8b-b463-da53b78db14f",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Purchased Packages",
                "normalized_name": "purchased_packages",
                "field_id": "97ad5f95-70ff-4018-abda-607ea0679f26",
                "field_type": "MULTI_SELECT",
            },
        ],
    },
    {
        "sales_template_name": "Rating Given",
        "normalized_name": "rating_given",
        "sales_template_id": "4f1f5b50-83db-4361-9776-7b128dc23a4a",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "6d245505-aa65-4f0e-b6ac-90d8e3943632",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "d5a4dac6-6f71-4b67-b09c-6e4aed3e04ca",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Rating Given",
                "normalized_name": "rating_given",
                "field_id": "23f76543-fd3c-4b36-a8b5-0135190dcdf8",
                "field_type": "INTEGER",
            },
        ],
    },
    {
        "sales_template_name": "Registered for Event",
        "normalized_name": "registered_for_event",
        "sales_template_id": "e520faf5-1023-48ef-933e-136c0a327d32",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "6d3132a2-2060-46ff-a54e-317ac68f3571",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Registered Event Name",
                "normalized_name": "registered_event_name",
                "field_id": "d78d253b-3612-4781-8208-12dae514db56",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Mobile Number",
                "normalized_name": "mobile_number",
                "field_id": "19b0fdee-1efe-410b-96d1-d0149f8375e2",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Gender",
                "normalized_name": "gender",
                "field_id": "ea2d8d6a-a3a0-492d-bbe8-47453bbf33de",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "924c442a-352b-4a40-ad5e-5640465b0f6c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Born on or before 1990?",
                "normalized_name": "born_on_or_before_1990",
                "field_id": "27b65254-bc7a-45d3-ab6d-d15b636ced18",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Registered Event ID",
                "normalized_name": "registered_event_id",
                "field_id": "5deaa1e8-7b78-4059-8b6a-5bc5aaa5873d",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Source",
                "normalized_name": "utm_source",
                "field_id": "7ded7469-be2c-4a3e-9239-d7e7e2fa4cb1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Medium",
                "normalized_name": "utm_medium",
                "field_id": "9522a519-44d4-40d3-90e7-d019e04ff08b",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Campaign",
                "normalized_name": "utm_campaign",
                "field_id": "7e7aacd3-bbb5-4909-b3e8-a31aa4b45b47",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Content",
                "normalized_name": "utm_content",
                "field_id": "2ea3514e-e901-4cc2-8892-551c1895c0b2",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Term",
                "normalized_name": "utm_term",
                "field_id": "29567db7-4c33-4fbf-b01e-da4f9a87c14f",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Scorecard and Highlights Status",
        "normalized_name": "scorecard_and_highlights_status",
        "sales_template_id": "b9edf56d-9424-4825-8379-daa1b26a0d99",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "a5ad3518-d212-44d5-ba57-9c7c55e8b094",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Clicked On Scorecard",
                "normalized_name": "clicked_on_scorecard",
                "field_id": "9ea04983-0a8f-4dc6-b45c-07c7a5793517",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Match Highlights",
                "normalized_name": "clicked_on_match_highlights",
                "field_id": "02927973-8cac-4239-8e4c-267dd2952c39",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "Website Visited",
        "normalized_name": "website_visited",
        "sales_template_id": "6017fa79-0275-4f5d-a6e9-26c8eefb24fb",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "e2756675-4e6a-4331-b4f6-8f7c5409f1f2",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Search",
                "normalized_name": "search",
                "field_id": "6082a899-dccb-4807-9dc6-94b913a823d7",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Referrer",
                "normalized_name": "referrer",
                "field_id": "7ece91ab-0ec2-4c1a-a630-ee89af8b7424",
                "field_type": "URL",
            },
            {
                "field_name": "Title",
                "normalized_name": "title",
                "field_id": "3c4f227b-ed0f-47ed-9c99-dfefe11451a1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Path",
                "normalized_name": "path",
                "field_id": "00806582-8dba-4d53-98f6-4bd5db91a3e4",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "URL",
                "normalized_name": "url",
                "field_id": "634fc0d1-a734-4fa6-ac88-10e3ad5d22e8",
                "field_type": "URL",
            },
        ],
    },
    {
        "sales_template_name": "Contact",
        "normalized_name": "contact",
        "sales_template_id": "eac72cc0-2639-4ee5-814f-1524530d01bb",
        "sales_template_type": "CONTACT",
        "fields": [
            {
                "field_name": "Last Name",
                "normalized_name": "last_name",
                "field_id": "9f619830-8678-4ea3-8acb-14f46da05294",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "First Name",
                "normalized_name": "first_name",
                "field_id": "bb44d230-fe3b-4b15-9ae8-5757ec5295fa",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Occupation",
                "normalized_name": "occupation",
                "field_id": "dcc72a76-b1ee-4637-a24b-7bfe92aa61e4",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Gender",
                "normalized_name": "gender",
                "field_id": "32abedc2-f7a3-4ea7-8ff9-230ab902cb21",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Born on or Before 1990?",
                "normalized_name": "born_on_or_before_1990",
                "field_id": "ba58211d-d4fd-47b8-ac82-32794f0520f8",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Phone Number",
                "normalized_name": "phone_number",
                "field_id": "46f8d28a-cd8f-4060-b384-3b3a047c2dae",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "WhatsApp Content Provided?",
                "normalized_name": "whatsapp_content_provided",
                "field_id": "3b7cdffd-c6be-452d-8abd-7e6734c4b001",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Assignee",
                "normalized_name": "assignee",
                "field_id": "159fd9c8-061c-4cca-bbba-fcb223db0973",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #1 Designation",
                "normalized_name": "contact_1_designation",
                "field_id": "0301cadb-9ca5-4558-b76b-e8b5c3418935",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 City",
                "normalized_name": "contact_1_city",
                "field_id": "0c34f16e-021b-48fc-86af-ce4712fb2a24",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact Type",
                "normalized_name": "contact_type",
                "field_id": "9d056362-feec-479f-b75d-5796c31cb10f",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Contact #2 Designation",
                "normalized_name": "contact_2_designation",
                "field_id": "969f6845-4925-4525-b712-c4d0deb08ccc",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #2 Phone Number",
                "normalized_name": "contact_2_phone_number",
                "field_id": "7718a0f8-53b4-4d69-a90e-465351097f5a",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Contact #3 Phone Number",
                "normalized_name": "contact_3_phone_number",
                "field_id": "94ab4d33-a8c8-4a59-96b0-d57584b950c4",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Other Host Type",
                "normalized_name": "other_host_type",
                "field_id": "7030c99b-757d-4194-a54f-cc20192d9633",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #1 Email",
                "normalized_name": "contact_1_email",
                "field_id": "3cae0e07-7dad-4745-9a22-54eb94c42005",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #2 Email",
                "normalized_name": "contact_2_email",
                "field_id": "72bafc4d-970c-4599-b991-d2cf434fa296",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #3 City",
                "normalized_name": "contact_3_city",
                "field_id": "1608be46-268e-4b9f-8240-8dfdc1b32c46",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Name",
                "normalized_name": "contact_3_name",
                "field_id": "3bb11a7e-f5f3-4dbc-adec-223eaac2c5db",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Host Type",
                "normalized_name": "host_type",
                "field_id": "58d8fe94-6c7c-4db6-a7d9-5c899054ff01",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Contact #3 Designation",
                "normalized_name": "contact_3_designation",
                "field_id": "d6b17b0b-6181-4c30-a8d4-e904061f9776",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Phone Number",
                "normalized_name": "contact_1_phone_number",
                "field_id": "a7d9d943-f151-4d78-bfec-7fc90f09d115",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Contact #2 Type - DM or POC",
                "normalized_name": "contact_2_type___dm_or_poc",
                "field_id": "fdfba2f4-4bcf-4a35-b41d-4ec9723af1a1",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Type - DM or POC",
                "normalized_name": "contact_3_type___dm_or_poc",
                "field_id": "b710c70e-6012-4a04-b523-38427cb5e937",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Type - DM or POC",
                "normalized_name": "contact_1_type___dm_or_poc",
                "field_id": "c9f80c32-1ebe-4b32-a88f-ce74fb4b209d",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #3 Email",
                "normalized_name": "contact_3_email",
                "field_id": "a7d9b799-e3ed-47a3-af12-0511ee916142",
                "field_type": "EMAIL",
            },
            {
                "field_name": "Contact #2 City",
                "normalized_name": "contact_2_city",
                "field_id": "e9115863-b73b-4c87-a7e5-3b10ec2f789c",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Contact #1 Name",
                "normalized_name": "contact_1_name",
                "field_id": "c5898766-1d52-44f6-986a-e5ef281014fc",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Contact #2 Name",
                "normalized_name": "contact_2_name",
                "field_id": "bb628f34-dfe3-4e05-ae5d-9581fbc05e5c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Address Line 1",
                "normalized_name": "address_line_1",
                "field_id": "132ef3cc-b5bc-46f6-a28d-fdc4dea01b16",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Address Line 2",
                "normalized_name": "address_line_2",
                "field_id": "88d4799e-173f-4745-95f5-db54829d8f8a",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "City",
                "normalized_name": "city",
                "field_id": "f603677d-eabb-4e01-86fd-9bff0d621dcc",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "State",
                "normalized_name": "state",
                "field_id": "54933d2b-d5f4-4cb6-bc60-67223dae60e3",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Pincode",
                "normalized_name": "pincode",
                "field_id": "c47f48c8-25a2-4763-a689-347f1b9697e2",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Landmark",
                "normalized_name": "landmark",
                "field_id": "9793925e-bc70-4ea8-b0a6-d3a9654135f6",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Custom Id",
                "normalized_name": "custom_id",
                "field_id": "9179a996-4405-493e-bd84-e47189c6b1e8",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Email",
                "normalized_name": "email",
                "field_id": "e6dadd33-ae80-4a84-94dc-ccbe14971c33",
                "field_type": "EMAIL",
            },
        ],
    },
    {
        "sales_template_name": "Lead",
        "normalized_name": "lead",
        "sales_template_id": "cd16c749-3d54-4df8-b153-60fdec54aa5a",
        "sales_template_type": "LEAD",
        "fields": [
            {
                "field_name": "Assignee",
                "normalized_name": "assignee",
                "field_id": "47ed0a89-e27b-4d23-b208-773dc0db29af",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Score",
                "normalized_name": "score",
                "field_id": "7af7d89c-e7fa-4dbf-bcdf-7431e457153a",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Stage",
                "normalized_name": "stage",
                "field_id": "9215af29-0ac2-4ef2-a43b-2eb0f45e5537",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced at Location",
                "normalized_name": "demo_experienced_at_location",
                "field_id": "fe69eb23-96a2-41bc-9e56-79795423215d",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced at City",
                "normalized_name": "demo_experienced_at_city",
                "field_id": "6a13b165-a415-40b5-83a1-f69bd66d3185",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Runs Scored in Demo",
                "normalized_name": "runs_scored_in_demo",
                "field_id": "e1a0e51d-cacb-4382-b78e-2a57ed676f3a",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Reason for Bad Experience",
                "normalized_name": "reason_for_bad_experience",
                "field_id": "c5889dda-7370-4d2d-a659-891d12bebc99",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "H.E Page Visited On",
                "normalized_name": "h_e_page_visited_on",
                "field_id": "4206a12d-4d1c-4a7c-9c72-38c3e86664a3",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Registered Event Name",
                "normalized_name": "registered_event_name",
                "field_id": "d70ea271-d85d-4591-9375-3b087ec177cb",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Registered Event ID",
                "normalized_name": "registered_event_id",
                "field_id": "fd7f1c16-2642-4b9b-a46f-369f598bdee1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Interest Status",
                "normalized_name": "interest_status",
                "field_id": "a3fef0f6-e108-4213-b279-e187dc412ce2",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Rating Given",
                "normalized_name": "rating_given",
                "field_id": "e6b1e1c6-fc5b-4878-9dc0-e1196da4f1af",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Challenges faced to purchase game",
                "normalized_name": "challenges_faced_to_purchase_game",
                "field_id": "1cedbe99-d4d3-4fa1-8d69-69ccb51edd81",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Conversion Probability Rating",
                "normalized_name": "conversion_probability_rating",
                "field_id": "1006b2d1-fa37-4a64-bc26-970c2302b535",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "What motivated him/her?",
                "normalized_name": "what_motivated_him_or_her",
                "field_id": "13c8977e-a839-4a26-be1f-e16713fd244f",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Next Follow-up Date",
                "normalized_name": "next_follow_up_date",
                "field_id": "b6f06fa9-63d1-41d1-b6c1-624c2f9ad0a6",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "H.E Page Visited",
                "normalized_name": "h_e_page_visited",
                "field_id": "74f1c8d9-e70c-487b-88ec-7c199da2abf9",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Commitment Status",
                "normalized_name": "commitment_status",
                "field_id": "f5eceed1-8ea5-427b-ad34-6962ebad8a6a",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "Call Status",
                "normalized_name": "call_status",
                "field_id": "53775f64-77d7-4b1c-bd2a-ff72d30bfdf6",
                "field_type": "FIELDS_SELECTOR",
            },
            {
                "field_name": "UTM Campaign",
                "normalized_name": "utm_campaign",
                "field_id": "4758aae6-f974-428e-ac6c-bbb5aabeb280",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Content",
                "normalized_name": "utm_content",
                "field_id": "862161ea-2791-4fbf-8c69-f38ad2a15ab0",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Medium",
                "normalized_name": "utm_medium",
                "field_id": "bcc14e30-cdd4-44f1-86e4-496ef0617c42",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Source",
                "normalized_name": "utm_source",
                "field_id": "33c8801d-427a-4e86-82fc-30b8b3f79115",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Term",
                "normalized_name": "utm_term",
                "field_id": "44f8808c-a018-442b-8254-9efca587cbd0",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Game Mode",
                "normalized_name": "game_mode",
                "field_id": "e34e120f-9e49-40e0-86ba-929d1c87dcdd",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Questions Asked",
                "normalized_name": "questions_asked",
                "field_id": "71eff3bf-516c-440a-ac36-dcc8249faf22",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Probable Purchase date",
                "normalized_name": "probable_purchase_date",
                "field_id": "03d6f1ef-e01c-4ba7-aa2a-3ed5fa818cd8",
                "field_type": "DATE",
            },
            {
                "field_name": "Describe the Resistance",
                "normalized_name": "describe_the_resistance",
                "field_id": "e2df053a-4fdf-4dfe-8051-e45940484d3a",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "Resistance to buy",
                "normalized_name": "resistance_to_buy",
                "field_id": "a911af61-0118-4ab1-92ea-2644021b5a44",
                "field_type": "MULTI_SELECT",
            },
            {
                "field_name": "Device Code",
                "normalized_name": "device_code",
                "field_id": "aa88d028-5d0f-4e03-8ead-7a2771d71d52",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "OperatorNumber",
                "normalized_name": "operatornumber",
                "field_id": "038f38d3-1034-41f8-bcd9-124ff089df14",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "OperatorName",
                "normalized_name": "operatorname",
                "field_id": "fe7b906e-2e5d-4067-972b-2d0f4f2abc86",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Lead Interest Status",
                "normalized_name": "bda_or_pes_lead_interest_status",
                "field_id": "42c4517c-330b-48dd-8684-fcd582159f56",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "BDA / PES Mobile Number",
                "normalized_name": "bda_or_pes_mobile_number",
                "field_id": "0275a374-7325-4f87-8128-13836a734141",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Remarks",
                "normalized_name": "bda_or_pes_remarks",
                "field_id": "910c02ea-4128-48ea-97c3-e7aa03ef5ca9",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "BDA / PES Name",
                "normalized_name": "bda_or_pes_name",
                "field_id": "ac4f3c1d-6472-48f0-84e4-ffec01e18ed1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Lead contest played status",
                "normalized_name": "lead_contest_played_status",
                "field_id": "e11385b7-c95c-48b9-8b8b-df073dfbbcab",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Scorecard",
                "normalized_name": "clicked_on_scorecard",
                "field_id": "eab80297-56f7-498e-af2a-e913ff875086",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Match Highlights",
                "normalized_name": "clicked_on_match_highlights",
                "field_id": "29cb548e-e9e6-481b-9954-6debc5717ce2",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "BDA / PES Feedback on Lead",
        "normalized_name": "bda_or_pes_feedback_on_lead",
        "sales_template_id": "08f5156d-b406-42b3-8bee-1bb5a9deafc7",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "17235138-371f-4d4c-a6b4-8784941ef54b",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "BDA / PES Lead Interest Status",
                "normalized_name": "bda_or_pes_lead_interest_status",
                "field_id": "ecb8c7b2-4f42-430c-8b2b-0a34f38d54f2",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "BDA / PES Mobile Number",
                "normalized_name": "bda_or_pes_mobile_number",
                "field_id": "1602f126-efce-40a8-836b-e1ca8942a82c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "BDA / PES Remarks",
                "normalized_name": "bda_or_pes_remarks",
                "field_id": "a86de4c9-d254-4650-9d4f-ef68bab4b9de",
                "field_type": "LONG_TEXT",
            },
            {
                "field_name": "BDA / PES Name",
                "normalized_name": "bda_or_pes_name",
                "field_id": "241cbd63-010c-4d6a-b097-fa25d3e33334",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Experienced the Demo",
        "normalized_name": "experienced_the_demo",
        "sales_template_id": "ef2368ab-3be4-4d12-ab35-7429f8724148",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "56bbbdef-6703-4552-91d9-fd6cd21978a1",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Demo Experienced At Location",
                "normalized_name": "demo_experienced_at_location",
                "field_id": "aa7f9b1f-45f4-4082-8e1f-5a10b1c300cf",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Demo Experienced At City",
                "normalized_name": "demo_experienced_at_city",
                "field_id": "a437d302-4e84-44be-a7a4-bd0a01ccac37",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Runs Scored in the Demo",
                "normalized_name": "runs_scored_in_the_demo",
                "field_id": "cbb6a178-e64b-49ec-9e8f-3d91c1421795",
                "field_type": "INTEGER",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "43a79ded-a615-487c-b11a-8e78e581c673",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Game Mode",
                "normalized_name": "game_mode",
                "field_id": "b3b06ea4-faf5-4ded-b574-a4c29c7b568f",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Operator Number",
                "normalized_name": "operator_number",
                "field_id": "dfd2d31a-cc4a-4a27-a141-22dd0acabb8a",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Operator Name",
                "normalized_name": "operator_name",
                "field_id": "dc4b5689-df1b-47c9-a4d4-fc80bdb6f718",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Device Code",
                "normalized_name": "device_code",
                "field_id": "4d0f0980-d45f-468a-9c97-4098bd12b471",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Interested in H.E",
        "normalized_name": "interested_in_h_e",
        "sales_template_id": "2a3301a9-4a39-4f30-974d-8429a55c4424",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "c24b3a4b-ed65-4b10-ab08-6263258d0077",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Interest Status",
                "normalized_name": "interest_status",
                "field_id": "fb5316e3-653c-4950-ba1d-9c44db9c459e",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "5d0d0c2e-a176-44e1-9426-5964551bd27f",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Player Contest Completion Status",
        "normalized_name": "player_contest_completion_status",
        "sales_template_id": "3ab6eff6-d220-4936-bbc4-df7a8bd6bee8",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "deeeaa4f-69d2-4748-b5cb-166f19a55687",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Lead contest played status",
                "normalized_name": "lead_contest_played_status",
                "field_id": "d23cdd58-37f0-4c4b-8b43-11416b7c62e3",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "Purchased H.E",
        "normalized_name": "purchased_h_e",
        "sales_template_id": "5f0a87f1-726b-4352-87ef-21300f6154f1",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "4cce297f-586c-4fda-aaa4-46289864842e",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Purchase Order ID",
                "normalized_name": "purchase_order_id",
                "field_id": "afec3981-1093-4a8b-b463-da53b78db14f",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Purchased Packages",
                "normalized_name": "purchased_packages",
                "field_id": "97ad5f95-70ff-4018-abda-607ea0679f26",
                "field_type": "MULTI_SELECT",
            },
        ],
    },
    {
        "sales_template_name": "Rating Given",
        "normalized_name": "rating_given",
        "sales_template_id": "4f1f5b50-83db-4361-9776-7b128dc23a4a",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "6d245505-aa65-4f0e-b6ac-90d8e3943632",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "d5a4dac6-6f71-4b67-b09c-6e4aed3e04ca",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Rating Given",
                "normalized_name": "rating_given",
                "field_id": "23f76543-fd3c-4b36-a8b5-0135190dcdf8",
                "field_type": "INTEGER",
            },
        ],
    },
    {
        "sales_template_name": "Registered for Event",
        "normalized_name": "registered_for_event",
        "sales_template_id": "e520faf5-1023-48ef-933e-136c0a327d32",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "6d3132a2-2060-46ff-a54e-317ac68f3571",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Registered Event Name",
                "normalized_name": "registered_event_name",
                "field_id": "d78d253b-3612-4781-8208-12dae514db56",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Mobile Number",
                "normalized_name": "mobile_number",
                "field_id": "19b0fdee-1efe-410b-96d1-d0149f8375e2",
                "field_type": "PHONE_NUMBER",
            },
            {
                "field_name": "Gender",
                "normalized_name": "gender",
                "field_id": "ea2d8d6a-a3a0-492d-bbe8-47453bbf33de",
                "field_type": "DROPDOWN",
            },
            {
                "field_name": "Name",
                "normalized_name": "name",
                "field_id": "924c442a-352b-4a40-ad5e-5640465b0f6c",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Born on or before 1990?",
                "normalized_name": "born_on_or_before_1990",
                "field_id": "27b65254-bc7a-45d3-ab6d-d15b636ced18",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Registered Event ID",
                "normalized_name": "registered_event_id",
                "field_id": "5deaa1e8-7b78-4059-8b6a-5bc5aaa5873d",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Source",
                "normalized_name": "utm_source",
                "field_id": "7ded7469-be2c-4a3e-9239-d7e7e2fa4cb1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Medium",
                "normalized_name": "utm_medium",
                "field_id": "9522a519-44d4-40d3-90e7-d019e04ff08b",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Campaign",
                "normalized_name": "utm_campaign",
                "field_id": "7e7aacd3-bbb5-4909-b3e8-a31aa4b45b47",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Content",
                "normalized_name": "utm_content",
                "field_id": "2ea3514e-e901-4cc2-8892-551c1895c0b2",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "UTM Term",
                "normalized_name": "utm_term",
                "field_id": "29567db7-4c33-4fbf-b01e-da4f9a87c14f",
                "field_type": "PLAIN_TEXT",
            },
        ],
    },
    {
        "sales_template_name": "Scorecard and Highlights Status",
        "normalized_name": "scorecard_and_highlights_status",
        "sales_template_id": "b9edf56d-9424-4825-8379-daa1b26a0d99",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "a5ad3518-d212-44d5-ba57-9c7c55e8b094",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Clicked On Scorecard",
                "normalized_name": "clicked_on_scorecard",
                "field_id": "9ea04983-0a8f-4dc6-b45c-07c7a5793517",
                "field_type": "RADIO_GROUP",
            },
            {
                "field_name": "Clicked On Match Highlights",
                "normalized_name": "clicked_on_match_highlights",
                "field_id": "02927973-8cac-4239-8e4c-267dd2952c39",
                "field_type": "RADIO_GROUP",
            },
        ],
    },
    {
        "sales_template_name": "Website Visited",
        "normalized_name": "website_visited",
        "sales_template_id": "6017fa79-0275-4f5d-a6e9-26c8eefb24fb",
        "sales_template_type": "ACTIVITY",
        "fields": [
            {
                "field_name": "Activity DateTime",
                "normalized_name": "activity_datetime",
                "field_id": "e2756675-4e6a-4331-b4f6-8f7c5409f1f2",
                "field_type": "DATE_TIME",
            },
            {
                "field_name": "Search",
                "normalized_name": "search",
                "field_id": "6082a899-dccb-4807-9dc6-94b913a823d7",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Referrer",
                "normalized_name": "referrer",
                "field_id": "7ece91ab-0ec2-4c1a-a630-ee89af8b7424",
                "field_type": "URL",
            },
            {
                "field_name": "Title",
                "normalized_name": "title",
                "field_id": "3c4f227b-ed0f-47ed-9c99-dfefe11451a1",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "Path",
                "normalized_name": "path",
                "field_id": "00806582-8dba-4d53-98f6-4bd5db91a3e4",
                "field_type": "PLAIN_TEXT",
            },
            {
                "field_name": "URL",
                "normalized_name": "url",
                "field_id": "634fc0d1-a734-4fa6-ac88-10e3ad5d22e8",
                "field_type": "URL",
            },
        ],
    },
]

# b875a502-43f1-11ee-be56-0242ac120002
# ec7ee9d0-43f1-11ee-be56-0242ac120002
if __name__ == "__main__":
    obj = SQLQueryConversion(table_mappings, field_mappings)
    obj.get_converted_sql_query(queries[0])

# 10 th index